### ISSUE TITLE
Package Status

### ISSUE THREAD

**Issue by mileslucas** [romainFr/SubpixelRegistration.jl#9]
Hi! I'm wondering if this package is still actively maintained. I've noticed the most recent release was for Julia 0.7- I recently worked on a rewrite that has fewer allocations and is designed for the newer Julia versions https://github.com/JuliaHCI/SubpixelRegistration.jl

If you would like, I can incorporate those changes into a PR here and work on getting this package updated, since this is what is currently in the general registry.

If you are not interested in maintaining this any further, would it be possible if I took over development? I think there may be a way to simply transfer the package name by copying the UUID and updating the general registry with a breaking release.

Thanks for your time!

**Comment by romainFr** [comment]
Hi Miles,

Thanks for working on this! I'm indeed not maintaining it anymore. I've added you as a collaborator, so feel free to either maintaining it here or transferring it somewhere else. There was talk to integrate it to JuliaImages back in the day, that was stopped because the Matlab code wasn't licensed then. But the Matlab code is now licensed, so that would be an option.

Cheers
Romain

**Comment by mileslucas** [comment]
Romain, thanks for the quick response and the cooperation!

If you're okay with it, do you want to transfer ownership to the `JuliaHCI` organization? (I can't access this as a "maintainer"). Once it is there I can work on updating the CI and pull in changes from my repo. This requires a bit of work on my end but will retain the full Git history as well as avoid having to register a new package or manually edit the general registry.

**Comment by romainFr** [comment]
I transferred it to you, as I cannot transfer to an organization I don't have ownership rights to. Good luck!

**Comment by mileslucas** [comment]
Okay, I've merged everything together, added more tests docs, and examples. I'll be able to get v0.2.0 out as soon as the URL change is processed in the general registry. Thanks again for being so responsive, I appreciate it!
